routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [UserController::class, 'index']);
Route::get('/katalog', [UserController::class, 'katalog'])->name('katalog');
Route::get('/product/checkout/{idProduct}', [UserController::class, 'checkout']);
Route::post('/product/checkout/{idProduct}/booking', [UserController::class, 'bookingProduct'])->name('bookingProduct');
Route::get('/product/payout/{code}', [UserController::class, 'payout'])->name('payout');
Route::post('/product/payout/{code}/verify', [UserController::class, 'payoutVerify'])->name('payout.verify');
Route::get('/product/payout/{code}/success', [UserController::class, 'payoutSuccess'])->name('payout.success');

Route::resource('product', ProductController::class);
Route::resource('tips-trick', ArticleController::class);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile', [UserController::class, 'updateUserProfil'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;


    protected $guarded = ['id'];
    public function getRouteKeyName(): string
    {
        return 'slug';
    }
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Http\Requests\StoreArticleRequest;
use App\Http\Requests\UpdateArticleRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = [
            'articles' => Article::all()
        ];
        return view('pages.article.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.article.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreArticleRequest $request)
    {
        $validateData = [
            'title' => $request->title,
            'content' => $request->content,
            'slug' => Str::slug($request->title) . Str::random(5),
        ];
        $image = $request->file('image');

        $validateData['image'] = $image->store('article');
        $validateData['user_id'] = auth()->user()->id;
        $article = Article::create($validateData);

        return redirect()->route('tips-trick.index')->with('success', 'Article berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     */
    public function show($slug)
    {
        $article = Article::where('slug', $slug)->with('user')->first();
        return view('pages.article.show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($slug)
    {
        $article = Article::where('slug', $slug)->with('user')->first();
        return view('pages.article.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateArticleRequest $request, $slug)
    {
        $article = Article::where('slug', $slug)->with('user')->first();
        $validateData = [
            'title' => $request->title,
            'content' => $request->content,
        ];
        if ($request->file('image')) {
            if ($request->oldImage) {
                Storage::delete($request->oldImage);
            }
            $validateData['image'] = $request->file('image')->store('article');
        }
        $validateData['user_id'] = auth()->user()->id;
        $article->update($validateData);

        return redirect()->route('tips-trick.index')->with('success', 'Article berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($slug)
    {
        $article = Article::where('slug', $slug)->first();
        $article->delete();
        Storage::delete($article->image);
        return redirect()->route('tips-trick.index')->with('success', 'Article berhasil dihapus');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/pages/article/create.blade.php
<x-guest-layout>
    <x-nav-guest data='article' />
    <section class="container">
        <form class="my-14 w-full" action={{ route('tips-trick.store') }} method="POST" enctype="multipart/form-data">
            @csrf
            <p class="md:text-3xl text-lg font-bold mb-8">Buat Tips & Tricks</p>
            <div class="mb-6">
                <label for="base-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Judul</label>
                <input type="text" id="base-input" name="title" placeholder="Masukkan judul artikel"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                @error('title')
                    <span class="text-red-500 text-sm">{{ $message }}</span>
                @enderror
            </div>
            <div class="mb-6">
                <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                    for="default_size">Gambar</label>
                <img id="preview" class="hidden aspect-square object-cover w-72 mb-3 " alt="">
                <input
                    class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
                    id="default_size" type="file" name="image" onchange="previewImage(this);">
                @error('image')
                    <span class="text-red-500 text-sm">{{ $message }}</span>
                @enderror
            </div>
            <div class="mb-6">
                <label for="base-input"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Kontent</label>
                <textarea id="myeditorinstance" name="content" placeholder="Tulis Artikel disini"></textarea>
                @error('content')
                    <span class="text-red-500 text-sm">{{ $message }}</span>
                @enderror
            </div>
            <button type="submit"
                class="hover:bg-[#E5B299] border-2 border-[#E5B299] hover:text-white duration-200 px-8 py-2 rounded-xl font-bold w-full">Simpan
                Artikel</button>
        </form>
    </section>
    <x-footer />
    <script>
        function previewImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $('#preview')
                        .removeClass('hidden')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
</x-guest-layout>

resources/views/pages/article/edit.blade.php
<x-guest-layout>
    <x-nav-guest data='article' />
    <section class="container">
        <form class="my-14 w-full" action={{ route('tips-trick.update', $article->slug) }} method="POST"
            enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <p class="md:text-3xl text-lg font-bold mb-8">Buat Tips & Tricks</p>
            <div class="mb-6">
                <label for="base-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Judul</label>
                <input type="text" id="base-input" name="title" placeholder="Masukkan judul artikel"
                    value="{{ $article->title }}"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                @error('title')
                    <span class="text-red-500 text-sm">{{ $message }}</span>
                @enderror
            </div>
            <div class="mb-6">
                <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                    for="default_size">Gambar</label>
                <img id="preview" class=" aspect-square object-cover w-72 mb-3 "
                    src={{ asset('storage/' . $article->image) }} alt="">
                <input type="hidden" value={{ $article->image }} name="oldImage">
                <input
                    class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
                    id="default_size" type="file" name="image" onchange="previewImage(this);">
                @error('image')
                    <span class="text-red-500 text-sm">{{ $message }}</span>
                @enderror
            </div>
            <div class="mb-6">
                <label for="base-input"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Kontent</label>
                <textarea id="myeditorinstance" name="content" placeholder="Tulis Artikel disini">{{ $article->content }}</textarea>
                @error('content')
                    <span class="text-red-500 text-sm">{{ $message }}</span>
                @enderror
            </div>
            <button type="submit"
                class="hover:bg-[#E5B299] border-2 border-[#E5B299] hover:text-white duration-200 px-8 py-2 rounded-xl font-bold w-full">Simpan
                Artikel</button>
        </form>
    </section>
    <x-footer />
    <script>
        function previewImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $('#preview')
                        .removeClass('hidden')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
</x-guest-layout>

resources/views/pages/article/index.blade.php
<x-guest-layout>
    <x-nav-guest data='article' />
    <section class="container">
        <div class="flex flex-row justify-between mt-14 mb-5">
            <p class="md:text-2xl text-lg font-bold">Tips & Tricks</p>
            @if (auth()->user())
                <a href={{ route('tips-trick.create') }}
                    class="py-1 md:px-10 px-3 border border-[#E5B299] text-[#E5B299] font-bold rounded-3xl hover:bg-[#E5B299] hover:text-black">Buat
                    Baru</a>
            @endif
        </div>
        <div class="flex flex-wrap lg:justify-between md:justify-center gap-4 mb-20">
            @foreach ($articles as $item)
                <a href={{ route('tips-trick.show', $item->slug) }}
                    class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row  md:max-w-2xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 h-52 mb-10 hover:scale-[1.02] duration-100 group">
                    <img class="object-cover rounded-t-lg aspect-square h-52 md:rounded-none md:rounded-l-lg group-hover:brightness-90 duration-150"
                        src={{ asset('storage/' . $item->image) }} alt="">
                    <div class="flex flex-col gap-5 justify-between p-4 leading-normal">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                            {{ $item->title }}</h5>
                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{!! strip_tags(substr($item->content, 0, 120) . '...') !!}
                        </p>
                    </div>
                </a>
            @endforeach

        </div>
    </section>
    <x-footer />
</x-guest-layout>

resources/views/pages/article/show.blade.php
<x-guest-layout>
    <x-nav-guest data='article' />
    <section class="container">
        <div class=" mb-16 flex flex-col">
            <div class="px-20 flex justify-between items-center">
                <a href={{ route('tips-trick.index') }}
                    class="mt-12 mb-12 font-semibold px-5 border-2 hover:px-8 duration-150 border-[#9e7b6a] py-1 rounded-3xl">Kembali</a>
                @if (auth()->user()?->id == $article->user_id)
                    <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown"
                        class="text-white bg-[#9e7b6a] hover:bg-[#cc9f89] focus:ring-4 focus:outline-none focus:ring-[#9e7b6a] font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center h-fit"
                        type="button">Manage Article<svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none"
                            stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7">
                            </path>
                        </svg></button>
                    <!-- Dropdown menu -->
                    <div id="dropdown"
                        class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                        <ul class="py-2 text-sm text-gray-700 dark:text-gray-200"
                            aria-labelledby="dropdownDefaultButton">
                            <li>
                                <a href={{ route('tips-trick.edit', $article->slug) }}
                                    class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Edit
                                    Artikel</a>
                            </li>
                            <li>
                                <form
                                    class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                                    action={{ route('tips-trick.destroy', $article->slug) }} method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="">Hapus Artikel</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                @endif
            </div>
            <div class="flex md:flex-row justify-between gap-16 flex-col px-20">
                <div class="md:max-w-[50%] flex flex-col justify-between">
                    <p class=" text-[#9e7b6a]">Created At
                        <span class="font-bold">
                            {{ date('D, d M Y', strtotime($article->created_at)) }}
                    </p>
                    </span>
                    <p class="text-5xl text-[#9e7b6a] font-bold w-fit text-end">{{ $article->title }}</p>
                    <div class="flex flex-row gap-5">
                        <img class="w-12 aspect-square rounded-3xl"
                            src="https://source.unsplash.com/random/?Children/" />
                        <div class="flex flex-col ">
                            <p class="font-bold md:text-black text-slate-300 w-fit">
                                {{ $article->user->name }}
                            </p>
                            <p class="text-sm text-gray-400 w-fit">
                                {{ $article->user->email }}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="md:max-w-[50%]">
                    <img class="h-96" src={{ asset('storage/' . $article->image) }} alt="">

                </div>
            </div>
            <div class="mt-14 px-20">{!! $article->content !!}</div>
        </div>
    </section>
    <x-footer />
</x-guest-layout>