routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [UserController::class, 'index']);
Route::get('/katalog', [UserController::class, 'katalog'])->name('katalog');
Route::get('/product/checkout/{idProduct}', [UserController::class, 'checkout']);
Route::post('/product/checkout/{idProduct}/booking', [UserController::class, 'bookingProduct'])->name('bookingProduct');
Route::get('/product/payout/{code}', [UserController::class, 'payout'])->name('payout');
Route::post('/product/payout/{code}/verify', [UserController::class, 'payoutVerify'])->name('payout.verify');
Route::get('/product/payout/{code}/success', [UserController::class, 'payoutSuccess'])->name('payout.success');

Route::resource('product', ProductController::class);
Route::resource('tips-trick', ArticleController::class);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile', [UserController::class, 'updateUserProfil'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/pages/checkout.blade.php
<x-guest-layout>
    <form class=" flex lg:flex-row flex-col-reverse" method="POST" action={{ route('bookingProduct', $product->id) }}>
        @csrf
        <div class="flex-col lg:w-[50%] w-full md:px-36 px-10 py-14 bg-white border-r">
            <p class="text-4xl font-extrabold md:mb-12 mb-7 lg:block hidden">Chekcout</p>
            @if (!auth()->user())
                <div class="flex flex-col justify-between md:gap-5 gap-3 md:mb-9 mb-4">
                    <div class="flex flex-row justify-between items-center">
                        <p class="text-xl font-semibold">Kontak</p>
                        <small class="text-gray-500">Sudah punya akun? <a class="font-bold"
                                href="/login">Login</a></small>
                    </div>
                    <input
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                        id="no_hp" name="no_hp" type="text" placeholder="No. HP">
                    <input
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                        id="email" name="email" type="text" placeholder="Email">
                </div>
            @endif
            <div class="flex flex-col justify-between md:gap-5 gap-3 md:mb-9 mb-4">
                <p class="text-xl font-semibold">Metode Pengiriman</p>
                <div class="flex items-center pl-4 border border-gray-200 rounded dark:border-gray-700">
                    <input checked id="bordered-radio-1" type="radio" value="JNE" name="shipping"
                        class="w-4 h-4 text-[#E0C097] bg-gray-100 border-gray-300 focus:ring-[#E0C097] dark:focus:ring-[#E0C097] dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                    <label for="bordered-radio-1"
                        class="w-full py-4 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">JNE - REG (3-5
                        Hari Pengiriman)</label>
                </div>
                <div class="flex items-center pl-4 border border-gray-200 rounded dark:border-gray-700">
                    <input id="bordered-radio-2" type="radio" value="SiCepat" name="shipping"
                        class="w-4 h-4 text-[#E0C097] bg-gray-100 border-gray-300 focus:ring-[#E0C097] dark:focus:ring-[#E0C097] dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                    <label for="bordered-radio-2"
                        class="w-full py-4 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">SiCepat (2-4 Hari
                        Pengiriman)</label>
                </div>
            </div>
            <div class="flex flex-col justify-between md:gap-5 gap-3 md:mb-9 mb-4">
                <p class="text-xl font-semibold">Alamat Pengiriman</p>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline"
                    id="sender_name" name="sender_name" type="text" placeholder="Nama Lengkap">
                @error('sender_name')
                    <small class="text-red-500">{{ $message }}</small>
                @enderror
                <div class="flex md:flex-row flex-col md:gap-5 gap-3">
                    <input
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline"
                        id="address" name="address" type="text" placeholder="Alamat">
                    @error('address')
                        <small class="text-red-500">{{ $message }}</small>
                    @enderror
                    <input
                        class="shadow appearance-none border rounded w-32 py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline"
                        id="postal_code" name="postal_code" type="number" placeholder="Kode Pos">
                    @error('postal_code')
                        <small class="text-red-500">{{ $message }}</small>
                    @enderror
                </div>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline"
                    id="district" name="district" type="text" placeholder="Kecamatan">
                @error('district')
                    <small class="text-red-500">{{ $message }}</small>
                @enderror
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline"
                    id="city" name="city" type="text" placeholder="Kota/Kabupaten">
                @error('city')
                    <small class="text-red-500">{{ $message }}</small>
                @enderror
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-outline"
                    id="province" name="province" type="text" placeholder="Provinsi">
                @error('province')
                    <small class="text-red-500">{{ $message }}</small>
                @enderror
            </div>
            <div class="flex md:flex-row gap-3 justify-between">
                <a href="/katalog "
                    class="border-[3px] border-[#B4846C] px-10 py-2 rounded-3xl text-[#B4846C] font-bold text-center">Batal</a>
                <button type="submit" class="bg-[#B4846C] px-10 py-2 rounded-3xl text-white font-bold">Lanjut ke
                    Pembayaran</button>
            </div>
        </div>
        <div class="flex-col lg:w-[50%] w-full md:px-12 px-10 py-14 ">
            <p class="text-4xl font-extrabold md:mb-12 mb-7 lg:hidden block">Chekcout</p>

            <div class=" w-full lg:mt-14 shadow-xl rounded-md bg-white px-10 py-14">
                <div class="flex flex-row justify-between pb-8 px-4">
                    <!-- Slider main container -->
                    <div class="swiper w-40 aspect-square mx-0 ">
                        <!-- Additional required wrapper -->
                        <div class="swiper-wrapper">
                            @foreach ($product->image as $item)
                                <div class="swiper-slide flex justify-center">
                                    <img class="h-40" src={{ asset('storage/' . $item) }} alt="">
                                </div>
                            @endforeach
                        </div>
                        <div class="swiper-pagination"></div>
                    </div>
                    <div class="flex flex-col">
                        <p class="text-xl font-bold mb-3">{{ $product->name }}</p>
                        <div class="flex flex-row gap-4 h-20 pe-3">
                            <div class="flex flex-col justify-between">
                                <p class="ps-[8px]">Qty</p>
                                <input type="number" name="quantity" min="1" max="{{ $product->stock }}"
                                    maxLength="3" onkeyup="quantityChanged()"
                                    class="counter--output w-12 border-none bg-transparent focus:ring-yellow-600 focus:rounded-lg text-center"
                                    id="qty" placeholder="1">
                                @error('quantity')
                                    <small class="text-red-500">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="flex flex-col justify-between">

                                <p>Harga</p>
                                <p class="pb-[8px]">Rp. {{ number_format($product->price, 0, ',', '.') }}</p>
                            </div>
                        </div>
                        <div class="border-2 border-black mt-3" />
                    </div>
                </div>
            </div>
            <div class="flex flex-row rounded-md overflow-hidden mb-6 mx-3">
                <div class="flex flex-col justify-between bg-[#FCDEC0] py-3 px-5 w-[50%]">
                    <p class="font-bold text-xs">KESBEK 3.0 <span class="font-normal text-gray-500">up to 30%</span>
                    </p>
                    <p class="text-lg font-bold mt-2">Kode Promo</p>
                </div>
                <div class="w-[50%] bg-[#E5B299] flex justify-center">
                    <input type="text" class="border-none bg-transparent focus:ring-0 focus:border-none w-40">
                </div>
            </div>
            <div class="flex flex-row">
                <div class="flex flex-col gap-1">
                    <p class="font-bold">Total Pesanan</p>
                    <p class="font-bold">Biaya Pengiriman</p>
                    <p class="font-bold">Voucher</p>
                    <hr class="my-3 border-none">
                    <p class="font-bold">Total Bayar</p>

                </div>
                <div class="flex flex-col ml-auto gap-1">
                    <p class="font-bold" id="totalPesan">Rp. {{ number_format($product->price, 0, ',', '.') }}</p>
                    <p class="font-bold">Rp. 10.000</p>
                    <p class="font-bold">- Rp. 0</p>
                    <hr class="my-3 border-2 border-gray-500">
                    <p class="font-bold">Rp. {{ number_format($product->price, 0, ',', '.') }}</p>
                </div>
            </div>
            </section>
</x-guest-layout>
<script>
    function quantityChanged() {
        let input = document.getElementById('qty')
        if (input.value < 1) {
            input.value = 1
        } else if (input.value > {{ $product->stock }}) {
            input.value = {{ $product->stock }}
        }
        document.getElementById('#totalPesan').innerHTML = 'aad'
    }
    // document.querySelectorAll('#qty').forEach(input => {
    //     input.oninput = () => {
    //         if (input.value < input.min) {
    //             input.value = input.min
    //         } else if (input.value > input.max) {
    //             input.value = input.max
    //         }
    //         if (input.value.length > input.maxLength) {
    //             input.value = input.value.slice(0, input.maxLength)
    //         }

    //     }
    //     document.querySelectorAll('#totalPesan').innerHTML = input.value
    // })
</script>
<script>
    const swiper = new Swiper('.swiper', {
        // Optional parameters
        direction: 'horizontal',
        loop: true,

        // If we need pagination
        pagination: {
            el: '.swiper-pagination',
        },
        autoplay: {
            delay: 4000,
            disableOnInteraction: false,
        },

    });
</script>

resources/views/pages/home.blade.php
<x-guest-layout>
    <div id="preloader" class=" min-h-screen min-w-full bg-black flex items-center fixed z-50">
        <img src={{ asset('images/loader.png') }} alt="">
        <div class="absolute flex flex-col gap-5 items-center w-full">
            <p class="text-white text-3xl font-bold">Ecothrift</p>
            <p class="text-white">Copyright Ecothrift 2023 | All right reserved. </p>
        </div>
    </div>
    <x-nav-guest />
    <section class="container">


        <!-- Slider main container -->
        <div class="swiper h-96 mt-10 rounded-lg overflow-hidden">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper ">
                <!-- Slides -->
                <div class="swiper-slide">
                    <img class="w-full lg:h-auto h-full object-cover" src={{ asset('images/slider/slider2.jpg') }}
                        alt="">
                </div>
                <div class="swiper-slide">
                    <img class="w-full lg:h-auto h-full object-cover" src={{ asset('images/slider/slider3.jpg') }}
                        alt="">
                </div>
                <div class="swiper-slide">
                    <img class="w-full lg:h-auto h-full object-cover" src={{ asset('images/slider/slider1.jpg') }}
                        alt="">
                </div>
            </div>
            <!-- If we need pagination -->
            <div class="swiper-pagination absolute !left-auto !right-10 bottom-0 !w-fit"></div>

        </div>
        <div class="flex flex-row justify-between mt-16">
            <p class="font-bold">Katalog</p>

            <div class="flex lg:flex-row flex-col gap-3">
                <a href="/katalog"
                    class="py-1 md:px-10 px-3 border border-[#E5B299] text-[#E5B299] font-bold rounded-3xl hover:bg-[#E5B299] hover:text-black">Tampilkan</a>
                @if (auth()->user())
                    <a href="/product/create"
                        class="py-1 md:px-10 px-3 border border-[#E5B299] text-[#E5B299] font-bold rounded-3xl hover:bg-[#E5B299] hover:text-black">Tambah
                        Produk</a>
                @endif

            </div>
        </div>
        <div class="flex md:flex-row flex-wrap gap-5 md:justify-between justify-center mt-10 mb-20">
            <div
                class="bg-white flex flex-col justify-center items-center gap-5 shadow-[5px_6px_20px_0_rgba(0,0,0,0.3)] rounded-xl w-80 h-80 hover:scale-105 duration-150">
                <img class="h-32" src={{ asset('images/women.png') }} alt="">
                <p>Pakaian Wanita</p>
                <a href="/katalog?kategori=Wanita"
                    class="bg-[#B4846C] hover:bg-[#98705B] cursor-pointer px-16 py-3 rounded-3xl w-fit text-white">Pilih</a>
            </div>
            <div
                class="bg-white flex flex-col justify-center items-center gap-5 shadow-[5px_6px_20px_0_rgba(0,0,0,0.3)] rounded-xl w-80 h-80 hover:scale-105 duration-150">
                <img class="h-32" src={{ asset('images/man.png') }} alt="">
                <p>Pakaian Pria</p>
                <a href="/katalog?kategori=Pria"
                    class="bg-[#B4846C] hover:bg-[#98705B] cursor-pointer px-16 py-3 rounded-3xl w-fit text-white">Pilih</a>
            </div>
            <div
                class="bg-white flex flex-col justify-center items-center gap-5 shadow-[5px_6px_20px_0_rgba(0,0,0,0.3)] rounded-xl w-80 h-80 hover:scale-105 duration-150">
                <img class="h-32" src={{ asset('images/child.png') }} alt="">
                <p>Pakaian Anak</p>
                <a href="/katalog?kategori=Anak"
                    class="bg-[#B4846C] hover:bg-[#98705B] cursor-pointer px-16 py-3 rounded-3xl w-fit text-white">Pilih</a>
            </div>
            <div
                class="bg-white flex flex-col justify-center items-center gap-5 shadow-[5px_6px_20px_0_rgba(0,0,0,0.3)] rounded-xl w-80 h-80 hover:scale-105 duration-150">
                <img class="h-32" src={{ asset('images/hat.png') }} alt="">
                <p>Accessories</p>
                <a href="/katalog?kategori=Accessories"
                    class="bg-[#B4846C] hover:bg-[#98705B] cursor-pointer px-16 py-3 rounded-3xl w-fit text-white">Pilih</a>
            </div>

        </div>
    </section>
    <x-footer />
</x-guest-layout>
<script>
    var loader = document.getElementById("preloader");
    window.addEventListener('load', function(load) {
        window.removeEventListener('load', load, false);
        setTimeout(function() {
            loader.style.setProperty("display", "none", "important")
        }, 1500);
    }, false);
</script>
<script>
    const swiper = new Swiper('.swiper', {
        // Optional parameters
        direction: 'horizontal',
        loop: true,

        // If we need pagination
        pagination: {
            el: '.swiper-pagination',
        },
        autoplay: {
            delay: 4000,
            disableOnInteraction: false,
        },

    });
</script>

resources/views/pages/katalog.blade.php
<x-guest-layout>
    <x-nav-guest />
    <section class="container">
        @if (request('search'))
            <p class="mt-10 text-center">Hasil Pencarian dari : <span class="font-bold">{{ request('search') }}</span></p>
        @endif
        @if (app('request')->input('kategori') != null)

            <div class="flex flex-col">
                <div class="flex flex-row justify-between mt-12">
                    <p class="font-bold">Katalog Pakaian {{ app('request')->input('kategori') }}</p>
                    <a href="/katalog?kategori={{ app('request')->input('kategori') }}"
                        class="py-1 md:px-10 px-3 border border-[#E5B299] text-[#E5B299] font-bold rounded-3xl hover:bg-[#E5B299] hover:text-black">Tampilkan</a>
                </div>
                <div class="flex flex-wrap md:justify-start justify-center gap-4 my-5">
                    @foreach ($products as $product)
                        {{-- <a href={{ auth()->user()?->id == $product->user_id ? '/product/' . $product->id . '/edit' : 'checkout/' . $product->id }} --}}
                        <a href={{ route('product.show', $product->id) }}
                            class="flex flex-col items-center bg-white shadow-lg py-5 md:px-8 px-2 md:w-[240px] w-[170px] rounded-xl">
                            <img class="md:h-36 h-28 w-fit mb-2" src={{ asset('storage/' . $product->image) }}
                                alt="">
                            <p>{{ $product->name }}</p>
                            <p class="text-[#B4846C] font-bold">Rp. {{ number_format($product->price, 0, ',', '.') }}
                            </p>
                            <small class="text-gray-500 mt-4">Stock : {{ $product->stock }}</small>
                        </a>
                    @endforeach
                </div>
            </div>
        @else
            {{-- START KATALOG WANITA --}}

            <div class="flex flex-col">
                <div class="flex flex-row justify-between mt-12">
                    <p class="font-bold">Katalog Pakaian Wanita</p>
                    <a href="/katalog?kategori=Wanita"
                        class="py-1 md:px-10 px-3 border border-[#E5B299] text-[#E5B299] font-bold rounded-3xl hover:bg-[#E5B299] hover:text-black">Tampilkan</a>
                </div>
                <div class="flex flex-wrap md:justify-start justify-center gap-4 my-5">
                    @foreach ($products_women as $p_women)
                        {{-- <a href={{ auth()->user()?->id == $p_women->user_id ? '/product/' . $p_women->id . '/edit' : 'checkout/' . $p_women->id }} --}}
                        <a href={{ route('product.show', $p_women->id) }}
                            class="flex flex-col items-center bg-white shadow-lg py-5 md:px-8 px-2 md:w-[240px] w-[170px] rounded-xl">
                            <img class="md:h-36 h-28 w-fit mb-2" src={{ asset('storage/' . $p_women->image) }}
                                alt="">
                            <p>{{ $p_women->name }}</p>
                            <p class="text-[#B4846C] font-bold">Rp. {{ $p_women->price }}</p>
                            <small class="text-gray-500 mt-4">Stock : {{ $p_women->stock }}</small>
                        </a>
                    @endforeach
                </div>
            </div>

            {{-- END KATALOG WANITA --}}

            {{-- START KATALOG PRIA --}}

            <div class="flex flex-col">
                <div class="flex flex-row justify-between mt-16">
                    <p class="font-bold">Katalog Pakaian Pria</p>
                    <a href="/katalog?kategori=Pria"
                        class="py-1 md:px-10 px-3 border border-[#E5B299] text-[#E5B299] font-bold rounded-3xl hover:bg-[#E5B299] hover:text-black">Tampilkan</a>
                </div>
                <div class="flex flex-wrap md:justify-start justify-center gap-4 my-5">
                    @foreach ($products_man as $p_men)
                        {{-- <a href={{ auth()->user()?->id == $p_men->user_id ? '/product/' . $p_men->id . '/edit' : 'checkout/' . $p_men->id }} --}}
                        <a href={{ route('product.show', $p_men->id) }}
                            class="flex flex-col items-center bg-white shadow-lg py-5 md:px-8 px-2 md:w-[240px] w-[170px] rounded-xl">
                            <img class="md:h-36 h-28 w-fit mb-2" src={{ asset('storage/' . $p_men->image) }}
                                alt="">
                            <p>{{ $p_men->name }}</p>
                            <p class="text-[#B4846C] font-bold">Rp. {{ $p_men->price }}</p>
                            <small class="text-gray-500 mt-4">Stock : {{ $p_men->stock }}</small>
                        </a>
                    @endforeach
                </div>
            </div>
            {{-- END KATALOG PRIA --}}

            {{-- START KATALOG ANAK --}}

            <div class="flex flex-col">
                <div class="flex flex-row justify-between mt-16">
                    <p class="font-bold">Katalog Pakaian Anak</p>
                    <a href="/katalog?kategori=Anak"
                        class="py-1 md:px-10 px-3 border border-[#E5B299] text-[#E5B299] font-bold rounded-3xl hover:bg-[#E5B299] hover:text-black">Tampilkan</a>
                </div>
                <div class="flex flex-wrap md:justify-start justify-center gap-4 my-5">
                    @foreach ($products_kids as $p_kids)
                        {{-- <a href={{ auth()->user()?->id == $p_kids->user_id ? '/product/' . $p_kids->id . '/edit' : 'checkout/' . $p_kids->id }} --}}
                        <a href={{ route('product.show', $p_kids->id) }}
                            class="flex flex-col items-center bg-white shadow-lg py-5 md:px-8 px-2 md:w-[240px] w-[170px] rounded-xl">
                            <img class="md:h-36 h-28 w-fit mb-2" src={{ asset('storage/' . $p_kids->image) }}
                                alt="">
                            <p>{{ $p_kids->name }}</p>
                            <p class="text-[#B4846C] font-bold">Rp. {{ $p_kids->price }}</p>
                            <small class="text-gray-500 mt-4">Stock : {{ $p_kids->stock }}</small>
                        </a>
                    @endforeach
                </div>
            </div>
            {{-- END KATALOG ANAK --}}

            {{-- START KATALOG Accessories --}}

            <div class="flex flex-col">
                <div class="flex flex-row justify-between mt-16">
                    <p class="font-bold">Katalog Pakaian Accessories</p>
                    <a href="/katalog?kategori=Accessories"
                        class="py-1 md:px-10 px-3 border border-[#E5B299] text-[#E5B299] font-bold rounded-3xl hover:bg-[#E5B299] hover:text-black">Tampilkan</a>
                </div>
                <div class="flex flex-wrap md:justify-start justify-center gap-4 my-5">
                    @foreach ($products_accessories as $p_acces)
                        {{-- <a href={{ auth()->user()?->id == $p_acces->user_id ? '/product/' . $p_acces->id . '/edit' : 'checkout/' . $p_acces->id }} --}}
                        <a href={{ route('product.show', $p_acces->id) }}
                            class="flex flex-col items-center bg-white shadow-lg py-5 md:px-8 px-2 md:w-[240px] w-[170px] rounded-xl">
                            <img class="md:h-36 h-28 w-fit mb-2" src={{ asset('storage/' . $p_acces->image) }}
                                alt="">
                            <p>{{ $p_acces->name }}</p>
                            <p class="text-[#B4846C] font-bold">Rp. {{ $p_acces->price }}</p>
                            <small class="text-gray-500 mt-4">Stock : {{ $p_acces->stock }}</small>
                        </a>
                    @endforeach
                </div>
            </div>
            {{-- END KATALOG Accessories --}}
        @endif
    </section>
    <x-footer />
</x-guest-layout>

resources/views/pages/payoutSuccess.blade.php
<x-guest-layout>
    <div class="bg-contain absolute w-full" style="background-image: url({{ asset('images/success.png') }})">
        <p class="text-3xl text-white font-extrabold px-16 py-8">Ecothrift</p>
    </div>
    <div class="flex flex-col justify-center items-center w-full min-h-screen">
        <p class="text-3xl font-bold mb-12">Transaksi Berhasil</p>
        <img class="aspect-square w-20" src={{ asset('images/check.png') }} alt="">
    </div>
    <script>
        window.setTimeout(function() {
            window.location.href = '/katalog';
        }, 3000);
    </script>
</x-guest-layout>